### PR TITLE
Update docs and add dist for changes

### PR DESCRIPTION
**Pull request by toddrun**
# What?

- Trying to hobble together a release to enable Material UI work (https://fulcrumapp.atlassian.net/browse/FLCRM-7225) 

# Why?

We need access to the hyperlink objects in fulcrum-core

# Testing

- More of a "look it over" kinda ticket

### CODE REVIEW

**Review by pedrolopez — APPROVED** [review]

**Review by KaraFox — COMMENTED** [review]
should we bump the package version with this?

**Review by jahndis — APPROVED** [review]

**Review by jahndis — CHANGES_REQUESTED** [review]
Double checking something...

**Comment by toddrun** [comment]
> If the npm package has already been published without generating the dist for index.js, then yes you will want to bump the package.json version so you can publish again.

We bumped the version cuz it seemed like the right thing to do . . . but we didn't have any idea what the other steps were. So we just took care of one of the publish steps _before_ we were actually running through the publishing steps. Sorry for the confusion.

**Review by jahndis — APPROVED** [review]
Alright it looks like you're good to NOT bump the version again. Just double checking a few things. You should be good to go with the normal process.

**Pull request merged**
